/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_riemannlee_rtmpproject_StreamProcessManager */

#ifndef _Included_StreamProcess
#define _Included_StreamProcess
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_init
        (JNIEnv *, jclass, jint, jint, jint, jint);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_release
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_yuvI420ToNV21
(JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_compressYUV
(JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint, jint, jint, jboolean);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_cropYUV
(JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint, jint, jint);


JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_encoderVideoinit
        (JNIEnv *, jclass, jint jinwidth, jint jinheight, jint joutwidth, jint joutheight);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_encoderVideoEncode
        (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jintArray);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_encoderAudioInit
        (JNIEnv *, jclass, jint, jint, jint);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_encoderAudioEncode
        (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_initRtmpData
        (JNIEnv *, jclass, jstring);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_sendRtmpVideoSpsPPS
        (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jlong);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_sendRtmpVideoData
        (JNIEnv *, jclass, jbyteArray, jint, jlong);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_sendRtmpAudioSpec
        (JNIEnv *, jclass,jlong);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_sendRtmpAudioData
        (JNIEnv *, jclass, jbyteArray, jint, jlong);

JNIEXPORT jint JNICALL Java_com_riemannlee_liveproject_StreamProcessManager_releaseRtmp
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
